name: ts_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appcenter:
  appcenter_analytics:
  appcenter_crashes:
 

  provider: ^5.0.0
  form_field_validator: ^1.1.0
  fluttertoast: ^8.0.5
  flutter_svg: ^0.21.0+1
  persistent_bottom_nav_bar: ^3.1.0
  random_string: ^2.1.0
  random_words: ^1.0.2
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  

flutter_icons:
ios: true
android: true
image_path: "assets/facebook_icon.png"   


flutter:

  uses-material-design: true
  
  assets:
    - assets/toast_icon_info.svg/
    - assets/toast_icon_success.svg/
    - assets/toast_icon_error.svg/
    - assets/toast_icon_close.svg/
    - assets/business_plan.jpg/
    - assets/facebook_icon.png/



  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Black.ttf
          weight: 500
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700